# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dx_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 707)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/me.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 65))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_top.setStyleSheet("background-color: transparent;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_toggle = QtWidgets.QFrame(self.frame_top)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_toggle.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_toggle_menu = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu.setSizePolicy(sizePolicy)
        self.btn_toggle_menu.setStyleSheet("QPushButton {\n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-menu.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu.setText("")
        self.btn_toggle_menu.setObjectName("btn_toggle_menu")
        self.verticalLayout_3.addWidget(self.btn_toggle_menu)
        self.horizontalLayout_3.addWidget(self.frame_toggle)
        self.frame_top_right = QtWidgets.QFrame(self.frame_top)
        self.frame_top_right.setStyleSheet("background: transparent;")
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_top_right)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top_btns = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_top_btns.setStyleSheet("background-color: rgba(27, 29, 35, 200)")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_top_btns.sizePolicy().hasHeightForWidth())
        self.frame_label_top_btns.setSizePolicy(sizePolicy)
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_6.setContentsMargins(5, 0, 10, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame.setMaximumSize(QtCore.QSize(30, 30))
        self.frame.setStyleSheet("background: transparent;\n"
"background-image: url(:/images_icons_20/images/icons/20x20/cil-3d.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6.addWidget(self.frame)
        self.label = QtWidgets.QLabel(self.frame_label_top_btns)
        self.label.setStyleSheet("background: transparent;")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btns_right.sizePolicy().hasHeightForWidth())
        self.frame_btns_right.setSizePolicy(sizePolicy)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images_icons_20/images/icons/20x20/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_maximize_restore.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_maximize_restore.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_maximize_restore.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images_icons_20/images/icons/20x20/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore.setIcon(icon2)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_5.addWidget(self.btn_maximize_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images_icons_20/images/icons/20x20/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon3)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_btns_right)
        self.verticalLayout.addWidget(self.frame_top_btns)
        self.frame_top_info = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_info.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_top_info.setStyleSheet("background-color: rgb(39, 44, 54);")
        self.frame_top_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_info.setObjectName("frame_top_info")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top_info)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_top_info_1 = QtWidgets.QLabel(self.frame_top_info)
        self.label_top_info_1.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_top_info_1.setStyleSheet("color: rgb(98, 103, 111); ")
        self.label_top_info_1.setObjectName("label_top_info_1")
        self.horizontalLayout.addWidget(self.label_top_info_1)
        self.label_top_info_2 = QtWidgets.QLabel(self.frame_top_info)
        self.label_top_info_2.setMaximumSize(QtCore.QSize(250, 20))
        self.label_top_info_2.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_top_info_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_top_info_2.setObjectName("label_top_info_2")
        self.horizontalLayout.addWidget(self.label_top_info_2)
        self.verticalLayout.addWidget(self.frame_top_info)
        self.horizontalLayout_3.addWidget(self.frame_top_right)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_center.sizePolicy().hasHeightForWidth())
        self.frame_center.setSizePolicy(sizePolicy)
        self.frame_center.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_center)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_menus)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_dc_run = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dc_run.sizePolicy().hasHeightForWidth())
        self.pushButton_dc_run.setSizePolicy(sizePolicy)
        self.pushButton_dc_run.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_dc_run.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-monitor.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(27, 29, 35);\n"
"    border-right: 5px solid rgb(44, 49, 60);\n"
"    background-color: rgb(27, 29, 35);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 28px solid rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.pushButton_dc_run.setObjectName("pushButton_dc_run")
        self.verticalLayout_8.addWidget(self.pushButton_dc_run)
        self.pushButton_weather = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_weather.sizePolicy().hasHeightForWidth())
        self.pushButton_weather.setSizePolicy(sizePolicy)
        self.pushButton_weather.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_weather.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-rain.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(27, 29, 35);\n"
"    background-color: rgb(27, 29, 35);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 28px solid rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.pushButton_weather.setObjectName("pushButton_weather")
        self.verticalLayout_8.addWidget(self.pushButton_weather)
        self.pushButton_config = QtWidgets.QPushButton(self.frame_menus)
        self.pushButton_config.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_config.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-equalizer.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(27, 29, 35);\n"
"    background-color: rgb(27, 29, 35);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 28px solid rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.pushButton_config.setObjectName("pushButton_config")
        self.verticalLayout_8.addWidget(self.pushButton_config)
        self.pushButton_about = QtWidgets.QPushButton(self.frame_menus)
        self.pushButton_about.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_about.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-comment-bubble.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(27, 29, 35);\n"
"    background-color: rgb(27, 29, 35);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 28px solid rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.pushButton_about.setObjectName("pushButton_about")
        self.verticalLayout_8.addWidget(self.pushButton_about)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.frame_menus)
        self.frame_extra_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_extra_menus.setMaximumSize(QtCore.QSize(16777215, 85))
        self.frame_extra_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extra_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extra_menus.setObjectName("frame_extra_menus")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_extra_menus)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 25)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.frame_extra_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/images/images/me.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border-radius: 30px;\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 5px solid rgb(39, 44, 54);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.verticalLayout_4.addWidget(self.frame_extra_menus)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_content_right = QtWidgets.QFrame(self.frame_center)
        self.frame_content_right.setStyleSheet("background-color: rgb(44, 49, 60);")
        self.frame_content_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_right.setObjectName("frame_content_right")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_content_right)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_content = QtWidgets.QFrame(self.frame_content_right)
        self.frame_content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_dc_run = QtWidgets.QWidget()
        self.page_dc_run.setObjectName("page_dc_run")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_dc_run)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.page_dc_run)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Pixel LCD7")
        font.setPointSize(28)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(85, 170, 255);\n"
"margin:1px;\n"
"background-color: rgb(33, 37, 43);")
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Pixel LCD7")
        font.setPointSize(28)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(85, 170, 255);\n"
"margin:1px;\n"
"background-color: rgb(33, 37, 43);")
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_dc_Info = QtWidgets.QLabel(self.frame_2)
        self.label_dc_Info.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_dc_Info.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"padding-right:6px;\n"
"margin:1px;\n"
"color: rgb(0, 255, 127);")
        self.label_dc_Info.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dc_Info.setObjectName("label_dc_Info")
        self.gridLayout.addWidget(self.label_dc_Info, 4, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_5.setStyleSheet("background-color:#d3b17d;\n"
"margin:1px;\n"
"color:#f3f9f1;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_6.setStyleSheet("background-color:#d3b17d;\n"
"margin:1px;\n"
"color:#f3f9f1;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_2.setStyleSheet("background-color:#d3b17d;\n"
"margin:1px;\n"
"color:#f3f9f1;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.page_dc_run)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_DC_FYRun_Down = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DC_FYRun_Down.sizePolicy().hasHeightForWidth())
        self.pushButton_DC_FYRun_Down.setSizePolicy(sizePolicy)
        self.pushButton_DC_FYRun_Down.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_DC_FYRun_Down.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_DC_FYRun_Down.setStyleSheet("QPushButton {\n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_DC_FYRun_Down.setText("")
        self.pushButton_DC_FYRun_Down.setObjectName("pushButton_DC_FYRun_Down")
        self.gridLayout_2.addWidget(self.pushButton_DC_FYRun_Down, 2, 1, 1, 1)
        self.pushButton_DC_FYRun_Up = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DC_FYRun_Up.sizePolicy().hasHeightForWidth())
        self.pushButton_DC_FYRun_Up.setSizePolicy(sizePolicy)
        self.pushButton_DC_FYRun_Up.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_DC_FYRun_Up.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_DC_FYRun_Up.setStyleSheet("QPushButton {\n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-arrow-top.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_DC_FYRun_Up.setText("")
        self.pushButton_DC_FYRun_Up.setObjectName("pushButton_DC_FYRun_Up")
        self.gridLayout_2.addWidget(self.pushButton_DC_FYRun_Up, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_8.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"margin:1px;\n"
"color: rgb(0, 255, 127);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)
        self.pushButton_DC_XHRun_Right = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DC_XHRun_Right.sizePolicy().hasHeightForWidth())
        self.pushButton_DC_XHRun_Right.setSizePolicy(sizePolicy)
        self.pushButton_DC_XHRun_Right.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_DC_XHRun_Right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_DC_XHRun_Right.setStyleSheet("QPushButton {\n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-arrow-right.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_DC_XHRun_Right.setText("")
        self.pushButton_DC_XHRun_Right.setObjectName("pushButton_DC_XHRun_Right")
        self.gridLayout_2.addWidget(self.pushButton_DC_XHRun_Right, 2, 3, 1, 1)
        self.pushButton_DC_XHRun_Left = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DC_XHRun_Left.sizePolicy().hasHeightForWidth())
        self.pushButton_DC_XHRun_Left.setSizePolicy(sizePolicy)
        self.pushButton_DC_XHRun_Left.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_DC_XHRun_Left.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_DC_XHRun_Left.setStyleSheet("QPushButton {\n"
"    background-image: url(:/images_icons_20/images/icons/20x20/cil-arrow-left.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_DC_XHRun_Left.setText("")
        self.pushButton_DC_XHRun_Left.setObjectName("pushButton_DC_XHRun_Left")
        self.gridLayout_2.addWidget(self.pushButton_DC_XHRun_Left, 2, 2, 1, 1)
        self.pushButton_DC_XHRunCtl = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DC_XHRunCtl.sizePolicy().hasHeightForWidth())
        self.pushButton_DC_XHRunCtl.setSizePolicy(sizePolicy)
        self.pushButton_DC_XHRunCtl.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_DC_XHRunCtl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_DC_XHRunCtl.setStyleSheet("QPushButton {\n"
"    color: rgb(234,237,237);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_DC_XHRunCtl.setObjectName("pushButton_DC_XHRunCtl")
        self.gridLayout_2.addWidget(self.pushButton_DC_XHRunCtl, 1, 2, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_11.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"margin:1px;\n"
"color: rgb(0, 255, 127);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 2)
        self.pushButton_DC_FYRunCtl = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DC_FYRunCtl.sizePolicy().hasHeightForWidth())
        self.pushButton_DC_FYRunCtl.setSizePolicy(sizePolicy)
        self.pushButton_DC_FYRunCtl.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_DC_FYRunCtl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_DC_FYRunCtl.setStyleSheet("QPushButton {\n"
"    color: rgb(234,237,237);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_DC_FYRunCtl.setObjectName("pushButton_DC_FYRunCtl")
        self.gridLayout_2.addWidget(self.pushButton_DC_FYRunCtl, 1, 0, 1, 2)
        self.horizontalLayout_11.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page_dc_run)
        self.page_weather = QtWidgets.QWidget()
        self.page_weather.setObjectName("page_weather")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_weather)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_3 = QtWidgets.QFrame(self.page_weather)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(280, 240, 54, 12))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_weather)
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_setting)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.page_setting)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 130))
        self.label_15.setStyleSheet("background-image: url(:/images/images/setting_backpic.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"border-radius: 10px;")
        self.label_15.setText("")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"margin:1px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.verticalLayout_13.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_LocalInterface = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_LocalInterface.sizePolicy().hasHeightForWidth())
        self.comboBox_LocalInterface.setSizePolicy(sizePolicy)
        self.comboBox_LocalInterface.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_LocalInterface.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.comboBox_LocalInterface.setObjectName("comboBox_LocalInterface")
        self.gridLayout_3.addWidget(self.comboBox_LocalInterface, 0, 0, 1, 1)
        self.label_InterfaceIP = QtWidgets.QLabel(self.frame_7)
        self.label_InterfaceIP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_InterfaceIP.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.label_InterfaceIP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_InterfaceIP.setObjectName("label_InterfaceIP")
        self.gridLayout_3.addWidget(self.label_InterfaceIP, 0, 1, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout_3)
        self.verticalLayout_13.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_14.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setStyleSheet("background-image: url(:/images/images/setting_backpic.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"border-radius: 10px;")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.label_13 = QtWidgets.QLabel(self.frame_8)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_13.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"margin:1px;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.verticalLayout_13.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_4.setHorizontalSpacing(5)
        self.gridLayout_4.setVerticalSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_18.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 2, 1, 1)
        self.lineEdit_Remote_IP = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Remote_IP.sizePolicy().hasHeightForWidth())
        self.lineEdit_Remote_IP.setSizePolicy(sizePolicy)
        self.lineEdit_Remote_IP.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Remote_IP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_Remote_IP.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.lineEdit_Remote_IP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Remote_IP.setObjectName("lineEdit_Remote_IP")
        self.gridLayout_4.addWidget(self.lineEdit_Remote_IP, 1, 1, 1, 1)
        self.lineEdit_Remote_Port = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Remote_Port.sizePolicy().hasHeightForWidth())
        self.lineEdit_Remote_Port.setSizePolicy(sizePolicy)
        self.lineEdit_Remote_Port.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Remote_Port.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_Remote_Port.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.lineEdit_Remote_Port.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Remote_Port.setObjectName("lineEdit_Remote_Port")
        self.gridLayout_4.addWidget(self.lineEdit_Remote_Port, 1, 3, 1, 1)
        self.lineEdit_Local_IP = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Local_IP.sizePolicy().hasHeightForWidth())
        self.lineEdit_Local_IP.setSizePolicy(sizePolicy)
        self.lineEdit_Local_IP.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Local_IP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_Local_IP.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.lineEdit_Local_IP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Local_IP.setObjectName("lineEdit_Local_IP")
        self.gridLayout_4.addWidget(self.lineEdit_Local_IP, 0, 1, 1, 1)
        self.lineEdit_Local_Port = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Local_Port.sizePolicy().hasHeightForWidth())
        self.lineEdit_Local_Port.setSizePolicy(sizePolicy)
        self.lineEdit_Local_Port.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Local_Port.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_Local_Port.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.lineEdit_Local_Port.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Local_Port.setObjectName("lineEdit_Local_Port")
        self.gridLayout_4.addWidget(self.lineEdit_Local_Port, 0, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_16.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.pushButton_udpSend = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_udpSend.sizePolicy().hasHeightForWidth())
        self.pushButton_udpSend.setSizePolicy(sizePolicy)
        self.pushButton_udpSend.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pushButton_udpSend.setStyleSheet("QPushButton {\n"
"    color: rgb(234,237,237);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_udpSend.setObjectName("pushButton_udpSend")
        self.gridLayout_4.addWidget(self.pushButton_udpSend, 2, 0, 1, 2)
        self.pushButton_udpSend_continue = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_udpSend_continue.sizePolicy().hasHeightForWidth())
        self.pushButton_udpSend_continue.setSizePolicy(sizePolicy)
        self.pushButton_udpSend_continue.setMaximumSize(QtCore.QSize(16777215, 120))
        self.pushButton_udpSend_continue.setStyleSheet("QPushButton {\n"
"    color: rgb(234,237,237);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_udpSend_continue.setObjectName("pushButton_udpSend_continue")
        self.gridLayout_4.addWidget(self.pushButton_udpSend_continue, 2, 2, 1, 2)
        self.pushButton_bing = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bing.sizePolicy().hasHeightForWidth())
        self.pushButton_bing.setSizePolicy(sizePolicy)
        self.pushButton_bing.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pushButton_bing.setStyleSheet("\n"
"QPushButton {\n"
"    color: rgb(234,237,237);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_bing.setObjectName("pushButton_bing")
        self.gridLayout_4.addWidget(self.pushButton_bing, 0, 4, 2, 1)
        self.pushButton_udp_multicast = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_udp_multicast.sizePolicy().hasHeightForWidth())
        self.pushButton_udp_multicast.setSizePolicy(sizePolicy)
        self.pushButton_udp_multicast.setMaximumSize(QtCore.QSize(16777215, 70))
        self.pushButton_udp_multicast.setStyleSheet("\n"
"QPushButton {\n"
"    color: rgb(234,237,237);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_udp_multicast.setObjectName("pushButton_udp_multicast")
        self.gridLayout_4.addWidget(self.pushButton_udp_multicast, 2, 4, 1, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout_4)
        self.verticalLayout_13.addWidget(self.frame_9)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_setting)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_about)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_10 = QtWidgets.QFrame(self.page_about)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 370))
        self.frame_11.setStyleSheet("background-image: url(:/images/images/about_pic.jpg);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"border-radius: 10px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_5.addWidget(self.frame_11, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background: transparent;\n"
"")
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_10)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background: transparent;\n"
"")
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 1, 0, 1, 1)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.frame_10)
        self.commandLinkButton.setStyleSheet("QCommandLinkButton {    \n"
"    color: rgb(85, 170, 255);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(210, 210, 210);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: rgb(210, 210, 210);\n"
"    background-color: rgb(52, 58, 71);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images_icons_20/images/icons/20x20/cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon4)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.gridLayout_5.addWidget(self.commandLinkButton, 5, 0, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_5)
        self.verticalLayout_16.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.page_about)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.label_systemTime = QtWidgets.QLabel(self.frame_content)
        self.label_systemTime.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"padding: 5px;\n"
"padding-bottom: 7px;\n"
"margin-top: 8px;\n"
"color: rgb(255, 0, 127);")
        self.label_systemTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_systemTime.setObjectName("label_systemTime")
        self.verticalLayout_7.addWidget(self.label_systemTime)
        self.verticalLayout_6.addWidget(self.frame_content)
        self.frame_grip = QtWidgets.QFrame(self.frame_content_right)
        self.frame_grip.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_grip.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_grip.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_grip)
        self.horizontalLayout_7.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_label_bottom = QtWidgets.QFrame(self.frame_grip)
        self.frame_label_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_credits = QtWidgets.QLabel(self.frame_label_bottom)
        self.label_credits.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_credits.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_8.addWidget(self.label_credits)
        self.label_version = QtWidgets.QLabel(self.frame_label_bottom)
        self.label_version.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_version.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_8.addWidget(self.label_version)
        self.horizontalLayout_7.addWidget(self.frame_label_bottom)
        self.frame_size_grip = QtWidgets.QFrame(self.frame_grip)
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_size_grip.setStyleSheet("background: transparent;\n"
"background-image: url(:/images_icons_20/images/icons/20x20/cil-link-broken.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_7.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.frame_grip)
        self.horizontalLayout_2.addWidget(self.frame_content_right)
        self.verticalLayout_2.addWidget(self.frame_center)
        self.verticalLayout_9.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "霄哥的神秘工具"))
        self.label.setText(_translate("MainWindow", "霄哥的神秘工具"))
        self.label_top_info_1.setText(_translate("MainWindow", "一切只是因为好玩！"))
        self.label_top_info_2.setText(_translate("MainWindow", "| HOME"))
        self.pushButton_dc_run.setText(_translate("MainWindow", "DC远程控制"))
        self.pushButton_weather.setText(_translate("MainWindow", "天气查询"))
        self.pushButton_config.setText(_translate("MainWindow", "配置参数"))
        self.pushButton_about.setText(_translate("MainWindow", "软件设置"))
        self.label_9.setText(_translate("MainWindow", "0.00"))
        self.label_10.setText(_translate("MainWindow", "0.00"))
        self.label_dc_Info.setText(_translate("MainWindow", "Info"))
        self.label_5.setText(_translate("MainWindow", "旋回"))
        self.label_6.setText(_translate("MainWindow", "俯仰"))
        self.label_2.setText(_translate("MainWindow", "随动设备状态:未知"))
        self.label_8.setText(_translate("MainWindow", "俯仰"))
        self.pushButton_DC_XHRunCtl.setText(_translate("MainWindow", "启动"))
        self.label_11.setText(_translate("MainWindow", "旋回"))
        self.pushButton_DC_FYRunCtl.setText(_translate("MainWindow", "启动"))
        self.label_3.setText(_translate("MainWindow", "PAGE 2"))
        self.label_4.setText(_translate("MainWindow", "网卡设置"))
        self.label_InterfaceIP.setText(_translate("MainWindow", "IP:255.255.255.255"))
        self.label_13.setText(_translate("MainWindow", "UDP协议设置"))
        self.label_18.setText(_translate("MainWindow", "本地Port："))
        self.label_17.setText(_translate("MainWindow", "远程IP："))
        self.label_19.setText(_translate("MainWindow", "远程Port："))
        self.lineEdit_Remote_IP.setPlaceholderText(_translate("MainWindow", "224.100.23.200"))
        self.lineEdit_Remote_Port.setPlaceholderText(_translate("MainWindow", "6000"))
        self.lineEdit_Local_IP.setPlaceholderText(_translate("MainWindow", "192.168.41.4"))
        self.lineEdit_Local_Port.setPlaceholderText(_translate("MainWindow", "6000"))
        self.label_16.setText(_translate("MainWindow", "本地IP："))
        self.pushButton_udpSend.setText(_translate("MainWindow", "发送"))
        self.pushButton_udpSend_continue.setText(_translate("MainWindow", "连续发送"))
        self.pushButton_bing.setText(_translate("MainWindow", "绑定"))
        self.pushButton_udp_multicast.setText(_translate("MainWindow", "组播"))
        self.label_23.setText(_translate("MainWindow", "霄哥的神秘工具是一个简单程序应用的框架，其中包含了一些工作中需要使用的模拟器。"))
        self.label_24.setText(_translate("MainWindow", "官方网址："))
        self.label_22.setText(_translate("MainWindow", "Design by:Jack Din"))
        self.label_21.setText(_translate("MainWindow", "霄哥的神秘工具"))
        self.commandLinkButton.setText(_translate("MainWindow", "www.dx1023.com"))
        self.label_systemTime.setText(_translate("MainWindow", "00<small>d</small> 00<small>h</small> 00<small>m</small> 00<small>s"))
        self.label_credits.setText(_translate("MainWindow", "Design by: Jack Din"))
        self.label_version.setText(_translate("MainWindow", "v1.0.0"))
import dx_rc_rc
