# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Meter_Sel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_all = QtWidgets.QFrame(self.centralwidget)
        self.frame_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_all.setObjectName("frame_all")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_all)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_all)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_top.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.label = QtWidgets.QLabel(self.frame_top)
        self.label.setGeometry(QtCore.QRect(380, 4, 211, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_main = QtWidgets.QFrame(self.frame_all)
        self.frame_main.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.label_gague = QtWidgets.QLabel(self.frame_main)
        self.label_gague.setGeometry(QtCore.QRect(110, 130, 320, 240))
        font = QtGui.QFont()
        font.setFamily("Pixel LCD7")
        font.setPointSize(26)
        self.label_gague.setFont(font)
        self.label_gague.setStyleSheet("background-image: url(:/images/meter_images/90/meter_sel1.png);\n"
"background-repeat: no-repeat;")
        self.label_gague.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_gague.setLineWidth(0)
        self.label_gague.setText("")
        self.label_gague.setObjectName("label_gague")
        self.label_gague_2 = QtWidgets.QLabel(self.frame_main)
        self.label_gague_2.setGeometry(QtCore.QRect(560, 130, 320, 240))
        font = QtGui.QFont()
        font.setFamily("Pixel LCD7")
        font.setPointSize(26)
        self.label_gague_2.setFont(font)
        self.label_gague_2.setStyleSheet("background-image: url(:/images/meter_images/90/meter_sel2.png);\n"
"background-repeat: no-repeat;")
        self.label_gague_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_gague_2.setLineWidth(0)
        self.label_gague_2.setText("")
        self.label_gague_2.setObjectName("label_gague_2")
        self.pushButton_style_choose1 = QtWidgets.QPushButton(self.frame_main)
        self.pushButton_style_choose1.setGeometry(QtCore.QRect(170, 400, 171, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.pushButton_style_choose1.setFont(font)
        self.pushButton_style_choose1.setObjectName("pushButton_style_choose1")
        self.pushButton_style_choose2 = QtWidgets.QPushButton(self.frame_main)
        self.pushButton_style_choose2.setGeometry(QtCore.QRect(640, 400, 171, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.pushButton_style_choose2.setFont(font)
        self.pushButton_style_choose2.setObjectName("pushButton_style_choose2")
        self.verticalLayout_2.addWidget(self.frame_main)
        self.verticalLayout.addWidget(self.frame_all)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "智能表盘生成器"))
        self.pushButton_style_choose1.setText(_translate("MainWindow", "48表盘编辑"))
        self.pushButton_style_choose2.setText(_translate("MainWindow", "96表盘编辑"))
import Meter_images_rc
